import type { Abi, AbiParameter } from "../types";

export const CROSS_CHAIN_INTENT_PARAM = {
  name: "crossChainIntent",
  type: "tuple",
  internalType: "struct CrossChainIntent",
  components: [
    { name: "author", type: "address", internalType: "address" },
    { name: "validBefore", type: "uint256", internalType: "uint256" },
    { name: "nonce", type: "uint256", internalType: "uint256" },
    { name: "srcMToken", type: "address", internalType: "address" },
    { name: "srcAmount", type: "uint256", internalType: "uint256" },
    { name: "destinationChainId", type: "uint32", internalType: "uint32" },
    { name: "nativeOutcome", type: "uint256", internalType: "uint256" },
    { name: "outcomeToken", type: "address", internalType: "address" },
    { name: "outcomeAmount", type: "uint256", internalType: "uint256" },
  ],
} as const satisfies AbiParameter;

export const CROSS_CHAIN_INTENT_BOOK_ABI = [
  {
    type: "constructor",
    inputs: [{ name: "manager", type: "address", internalType: "address" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "intentStates",
    inputs: [{ name: "intentId", type: "bytes32", internalType: "bytes32" }],
    outputs: [{ name: "", type: "uint8", internalType: "enum IntentState" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "intents",
    inputs: [{ name: "intentId", type: "bytes32", internalType: "bytes32" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct CrossChainIntent",
        components: [
          { name: "author", type: "address", internalType: "address" },
          { name: "validBefore", type: "uint256", internalType: "uint256" },
          { name: "nonce", type: "uint256", internalType: "uint256" },
          { name: "srcMToken", type: "address", internalType: "address" },
          { name: "srcAmount", type: "uint256", internalType: "uint256" },
          { name: "destinationChainId", type: "uint32", internalType: "uint32" },
          { name: "nativeOutcome", type: "uint256", internalType: "uint256" },
          { name: "outcomeToken", type: "address", internalType: "address" },
          { name: "outcomeAmount", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "fulfillmentVerifier",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "mTokenManager",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "publish",
    inputs: [
      {
        name: "intent",
        type: "tuple",
        internalType: "struct CrossChainIntent",
        components: [
          { name: "author", type: "address", internalType: "address" },
          { name: "validBefore", type: "uint256", internalType: "uint256" },
          { name: "nonce", type: "uint256", internalType: "uint256" },
          { name: "srcMToken", type: "address", internalType: "address" },
          { name: "srcAmount", type: "uint256", internalType: "uint256" },
          { name: "destinationChainId", type: "uint32", internalType: "uint32" },
          { name: "nativeOutcome", type: "uint256", internalType: "uint256" },
          { name: "outcomeToken", type: "address", internalType: "address" },
          { name: "outcomeAmount", type: "uint256", internalType: "uint256" },
        ],
      },
      { name: "signature", type: "bytes", internalType: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "publishUnsigned",
    inputs: [
      {
        name: "intent",
        type: "tuple",
        internalType: "struct CrossChainIntent",
        components: [
          { name: "author", type: "address", internalType: "address" },
          { name: "validBefore", type: "uint256", internalType: "uint256" },
          { name: "nonce", type: "uint256", internalType: "uint256" },
          { name: "srcMToken", type: "address", internalType: "address" },
          { name: "srcAmount", type: "uint256", internalType: "uint256" },
          { name: "destinationChainId", type: "uint32", internalType: "uint32" },
          { name: "nativeOutcome", type: "uint256", internalType: "uint256" },
          { name: "outcomeToken", type: "address", internalType: "address" },
          { name: "outcomeAmount", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "settle",
    inputs: [{ name: "intentId", type: "bytes32", internalType: "bytes32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "cancel",
    inputs: [{ name: "intentId", type: "bytes32", internalType: "bytes32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "cancel",
    inputs: [
      { name: "intentId", type: "bytes32", internalType: "bytes32" },
      { name: "proof", type: "bytes", internalType: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setFulfillmentVerifier",
    inputs: [{ name: "_fulfillmentVerifier", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setMTokenManager",
    inputs: [{ name: "_mTokenManager", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "CrossChainIntentPublished",
    inputs: [
      { name: "intentId", type: "bytes32", indexed: true, internalType: "bytes32" },
      {
        name: "intent",
        type: "tuple",
        indexed: false,
        internalType: "struct CrossChainIntent",
        components: [
          { name: "author", type: "address", internalType: "address" },
          { name: "validBefore", type: "uint256", internalType: "uint256" },
          { name: "nonce", type: "uint256", internalType: "uint256" },
          { name: "srcMToken", type: "address", internalType: "address" },
          { name: "srcAmount", type: "uint256", internalType: "uint256" },
          { name: "destinationChainId", type: "uint32", internalType: "uint32" },
          { name: "nativeOutcome", type: "uint256", internalType: "uint256" },
          { name: "outcomeToken", type: "address", internalType: "address" },
          { name: "outcomeAmount", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CrossChainIntentSettled",
    inputs: [
      { name: "intentId", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "filler", type: "address", indexed: true, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CrossChainIntentCancelled",
    inputs: [
      { name: "intentId", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "author", type: "address", indexed: true, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "FulfillmentVerifierUpdated",
    inputs: [
      { name: "oldVerifier", type: "address", indexed: true, internalType: "address" },
      { name: "newVerifier", type: "address", indexed: true, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "MTokenManagerUpdated",
    inputs: [
      { name: "oldManager", type: "address", indexed: true, internalType: "address" },
      { name: "newManager", type: "address", indexed: true, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "error",
    name: "InvalidSignature",
    inputs: [],
  },
  {
    type: "error",
    name: "NoOutcomeMTokens",
    inputs: [],
  },
  {
    type: "error",
    name: "MismatchedOutcomeMTokensAndAmounts",
    inputs: [],
  },
  {
    type: "error",
    name: "InvalidAuthor",
    inputs: [],
  },
  {
    type: "error",
    name: "InvalidSrcMToken",
    inputs: [],
  },
  {
    type: "error",
    name: "InvalidSrcAmount",
    inputs: [],
  },
  {
    type: "error",
    name: "InvalidDestinationChainId",
    inputs: [],
  },
  {
    type: "error",
    name: "IntentAlreadyExists",
    inputs: [{ name: "intentId", type: "bytes32", internalType: "bytes32" }],
  },
  {
    type: "error",
    name: "IntentNotOpen",
    inputs: [{ name: "intentId", type: "bytes32", internalType: "bytes32" }],
  },
  {
    type: "error",
    name: "NoFiller",
    inputs: [{ name: "intentId", type: "bytes32", internalType: "bytes32" }],
  },
  {
    type: "error",
    name: "CannotCancel",
    inputs: [],
  },
  {
    type: "error",
    name: "ZeroAddress",
    inputs: [],
  },
  {
    type: "error",
    name: "InvalidOutcomeMToken",
    inputs: [{ name: "index", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "error",
    name: "InvalidOutcomeAmount",
    inputs: [{ name: "index", type: "uint256", internalType: "uint256" }],
  },
] as const satisfies Abi;
